version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: "mongodb://mongo:27017/movies-api"
      REDIS_HOST: "redis://redis:6379/0"
      REDIS_MAX_MEMORY: "102400000"
    restart: on-failure
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-volume:/data/db
  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-volume:/data
volumes:
  mongo-volume:
  redis-volume: